# Configuration file for taplo, our TOML formatter

include = [
  ".bumpversion.toml",
  ".coveragerc.toml",
  ".taplo.toml",
  "pyproject.toml",
  "pytest.toml",
  "ruff.toml",
]

[formatting]
align_entries = false
align_comments = false
column_width = 88
