name: 'Prepare CI'
description: 'Prepares an environment to run a set of Eradiate tests'
outputs:
  mitsuba-cache-hit:
    description: "Mitsuba cache hit"
    value: ${{ steps.cache.outputs.cache-hit }}
runs:
  using: "composite"

  steps:
  - name: Install Python
    uses: actions/setup-python@v5
    with:
      python-version: "3.12"
  - name: Install Chrome
    uses: browser-actions/setup-chrome@v1
  - name: Install dependencies
    shell: bash
    run: |
      python -m pip install --upgrade pip
      pip install .[doc,recommended,test,dev]
  - name: Get kernel hash
    shell: bash
    run: |
      echo "ext/mitsuba/build" >> $GITHUB_PATH
      cd ext/mitsuba
      echo "MITSUBA_HASH=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
  - name: Cache kernel build
    uses: actions/cache@v4
    with:
      path: ext/mitsuba/build
      key:
        mitsuba-${{ env.MITSUBA_HASH }}-${{ env.CACHE_NUMBER}}
    env:
      CACHE_NUMBER: 1
    id: cache
