name: 'Save CI Logs'
description: 'Save Robot log artefacts'
runs:
  using: "composite"

  steps:
    - name: Save HTML log
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: log_html
        path: ./log.html
    - name: Save HTML report
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: report_html
        path: ./report.html
    - name: Save PDF log
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: log_pdf
        path: ./log.pdf
    - name: Save PDF report
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: report_pdf
        path: ./report.pdf
    - name: Save test outputs
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: output_xml
        path: ./output.xml
