import pytest

import eradiate
from eradiate import unit_registry as ureg


@pytest.mark.parametrize("geometry", ["plane_parallel", "spherical_shell"])
def test_heterogeneous_parameter_consistency(
    modes_all_double, geometry, atmosphere_us_standard_mono, atmosphere_us_standard_ckd
):
    """
    *Scene parameter path consistency*

    This test checks if parameters belonging to objects referenced by Mitsuba
    ``Medium`` objects are correctly retrieved.

    Mitsuba's parameter lookup used to be unpredictable until v3.7.x. This has
    been significantly improved, and this test verifies that the paths under
    which entries appear in the scene parameter list is independent of the scene
    setup.

    For that purpose, we create an ``Experiment`` and populate it with an
    atmosphere and an *in situ* measure. This way, the ``Medium`` instance
    generated by the atmosphere configuration is referenced both by the
    atmosphere shape and the sensor.

    *Expected behaviour*

    The name under which the medium appears should be independent of the
    atmosphere or sensor.
    """
    atmosphere_mono = atmosphere_us_standard_mono
    atmosphere_mono.update({"has_scattering": False})

    atmosphere_ckd = atmosphere_us_standard_ckd
    atmosphere_ckd.update({"has_scattering": False})

    exp = eradiate.experiments.AtmosphereExperiment(
        geometry=geometry,
        surface={"type": "lambertian", "reflectance": 1.0},
        atmosphere=atmosphere_ckd if eradiate.mode().is_ckd else atmosphere_mono,
        illumination={"type": "directional", "zenith": 30.0},
        measures={
            "type": "distantflux",
            "id": "dflux",
            "srf": {"type": "delta", "wavelengths": 550.0 * ureg.nm},
            "ray_offset": 1.0 * ureg.m,
        },
    )
    exp.init()

    expected = (
        "medium_atmosphere.albedo.volume.data"
        if geometry == "spherical_shell"
        else "medium_atmosphere.albedo.data"
    )
    assert expected in exp.mi_scene.parameters
