from importlib import import_module
from pathlib import Path
from textwrap import dedent, indent

import eradiate
from eradiate._config import EradiateConfig, format_help_dicts_rst

# Auto-generation disclaimer text
HEADER = dedent(
    """
    ..
      This file was automatically generated by docs/generate_rst_api.py. The

          make docs-rst-api

      target automates this process.
    """
).strip()


def write_if_modified(filename, content):
    filename.parent.mkdir(parents=True, exist_ok=True)

    try:
        with open(filename, "r") as f:
            existing = f.read()
    except OSError:
        existing = None

    if existing == content:
        print(f"Skipping unchanged '{filename.name}'")

    else:
        print(f"Generating '{filename.name}'")
        with open(filename, "w") as f:
            f.write(content)


def generate_env_vars_docs():
    outdir = Path(__file__).parent.absolute() / "rst/reference_api/generated/env_vars"
    print(f"Generating environment variable docs in '{outdir}'")

    content = "\n".join(
        [
            HEADER,
            "",
            dedent(
                """
                .. _sec-config-env_vars:
    
                Environment variables
                ---------------------
                """
            ),
            EradiateConfig.generate_help(
                formatter=format_help_dicts_rst, display_defaults=True
            ),
            "",
        ]
    )

    write_if_modified(outdir / "env_vars.rst", content)


# List of (module, variable) pairs
FACTORIES = [
    ("eradiate.radprops", "rad_profile_factory"),
    ("eradiate.scenes.atmosphere", "atmosphere_factory"),
    ("eradiate.scenes.atmosphere", "particle_distribution_factory"),
    ("eradiate.scenes.biosphere", "biosphere_factory"),
    ("eradiate.scenes.bsdfs", "bsdf_factory"),
    ("eradiate.scenes.illumination", "illumination_factory"),
    ("eradiate.scenes.integrators", "integrator_factory"),
    ("eradiate.scenes.measure", "measure_factory"),
    ("eradiate.scenes.phase", "phase_function_factory"),
    ("eradiate.scenes.shapes", "shape_factory"),
    ("eradiate.scenes.spectra", "spectrum_factory"),
    ("eradiate.scenes.surface", "surface_factory"),
]


def factory_data_docs(modname, varname, uline="="):
    """
    Return rst code for a factory instance located at modname.varname.
    """
    factory = getattr(import_module(modname), varname)
    fullname = f"{modname}.{varname}"
    underline = uline * len(fullname)

    table_header = ".. list-table::\n   :widths: 25 75"
    table_rows = "\n".join(
        [
            f"   * - ``{key}``\n     - :class:`{entry.cls.__name__}`"
            for key, entry in sorted(factory.registry.items())
        ]
    )
    table = "\n".join([table_header, "", table_rows])

    return f"""{fullname}
{underline}

.. data:: {modname}.{varname}
   :annotation:

   Instance of :class:`{factory.__class__.__module__}.{factory.__class__.__qualname__}`

   .. rubric:: Registered types

{indent(table, "   ")}

""".lstrip()


def generate_factory_docs():
    """
    Generate rst documents to display factory documentation.
    """
    outdir = Path(__file__).parent.absolute() / "rst/reference_api/generated/factory"
    print(f"Generating factory docs in '{outdir}'")

    for modname, varname in FACTORIES:
        generated = factory_data_docs(modname, varname)
        content = "\n".join([HEADER, "", generated, ""])
        write_if_modified(outdir / f"{modname}.{varname}.rst", content)


def generate_context_docs():
    outdir = (
        Path(__file__).parent.absolute() / "rst/reference_api/generated/context_fields"
    )
    print(f"Generating dynamic context field docs in '{outdir}'")

    body = []

    for field in sorted(eradiate.contexts.KernelDictContext.DYNAMIC_FIELDS.data.keys()):
        methods = eradiate.contexts.KernelDictContext.DYNAMIC_FIELDS.data[field]

        body.append(f"{field}")
        body.append(
            indent(
                ",\n".join(
                    sorted(
                        f":meth:`.{'.'.join(method.split('.')[-2:])}`"
                        for method in methods
                    )
                ),
                "    ",
            )
        )
        body.append("")

    content = "\n".join(
        [
            HEADER,
            "",
            dedent(
                """
                .. _sec-contexts-context_fields:

                ``KernelDictContext``: List of registered dynamic context fields
                ----------------------------------------------------------------
                
                The dynamic field table held by 
                :attr:`.KernelDictContext.DYNAMIC_FIELDS` contains the following 
                entries:
                """
            ),
            "\n".join(body),
            "",
        ]
    )

    write_if_modified(outdir / "context_fields.rst", content)


if __name__ == "__main__":
    generate_factory_docs()
    generate_env_vars_docs()
    generate_context_docs()
