azimuth_convention = "east_right"
progress = "spectral_loop"
offline = false

[absorption_database.error_handling]
p = {missing = "raise", scalar = "raise", bounds = "ignore"}
t = {missing = "raise", scalar = "raise", bounds = "ignore"}
x = {missing = "ignore", scalar = "ignore", bounds = "raise"}
