name: Eradiate test

on:
  workflow_dispatch:
  pull_request:

env:
  CC: clang-17
  CXX: clang++-17
  ERADIATE_SOURCE_DIR: ${{ github.workspace }}
  PYTHONPATH: ${{ github.workspace }}/ext/mitsuba/build/python

jobs:
  robot:
    runs-on: [self-hosted, ars, ubuntu_x86_64_eradiatecompile_spot]
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "recursive"
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .[doc,recommended,test,dev]
      - name: Get kernel hash
        run: |
          echo "ext/mitsuba/build" >> $GITHUB_PATH
          cd ext/mitsuba
          echo "MITSUBA_HASH=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
      - name: Cache kernel build
        uses: actions/cache@v4
        with:
          path: ext/mitsuba/build
          key:
            mitsuba-${{ env.MITSUBA_HASH }}-${{ env.CACHE_NUMBER}}
        env:
          CACHE_NUMBER: 1
        id: cache
      - name: Build kernel
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          cmake -S ext/mitsuba -B ext/mitsuba/build -DCMAKE_BUILD_TYPE=Release -GNinja --preset eradiate
          cmake --build ext/mitsuba/build
      - name: Download datasets
        run: |
          eradiate data fetch minimal
          eradiate data fetch monotropa
          eradiate data fetch komodo
          eradiate data fetch gecko
      - name: Run fast tests
        run: |
          pytest -p robotframework --robot-tagstatinclude unit --robot-tagstatinclude system --robot-tagstatinclude regression --robot-tagstatinclude slow -m "not slow" ./tests
      - name: Robot report
        if: always()
        run: |
          rebot --expandkeywords name:* ./output.xml
          chrome --no-sandbox --virtual-time-budget=10000 --headless --print-to-pdf=./log.pdf    ./log.html    --no-pdf-header-footer
          chrome --no-sandbox --virtual-time-budget=10000 --headless --print-to-pdf=./report.pdf ./report.html --no-pdf-header-footer
      - name: Save HTML log
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: log_html
          path: ./log.html
      - name: Save HTML report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: report_html
          path: ./report.html
      - name: Save PDF log
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: log_pdf
          path: ./log.pdf
      - name: Save PDF report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: report_pdf
          path: ./report.pdf
      - name: Save test outputs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: output_xml
          path: ./output.xml
