name: Eradiate CI

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review

env:
  CC: clang-17
  CXX: clang++-17
  ERADIATE_SOURCE_DIR: ${{ github.workspace }}
  PYTHONPATH: ${{ github.workspace }}/ext/mitsuba/build/python

jobs:
  compile:
    name: Build kernel
    runs-on: [self-hosted, ars, ubuntu_x86_64_eradiatecompile_spot]

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "recursive"
      - id: prepare
        uses: ./.github/actions/prepare-ci
      - name: Build kernel
        if: steps.prepare.outputs.mitsuba-cache-hit != 'true'
        run: |
          cmake -S ext/mitsuba -B ext/mitsuba/build -DCMAKE_BUILD_TYPE=Release -GNinja --preset eradiate
          cmake --build ext/mitsuba/build

  test:
    name: Run tests (routine only)
    needs: compile
    runs-on: [self-hosted, ars, ubuntu_x86_64_eradiateci_spot]
    if: github.event.pull_request.draft == true

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "recursive"
      - id: prepare
        uses: ./.github/actions/prepare-ci
      - name: Download datasets
        run: |
          eradiate data install core
      - name: Eradiate show
        run: |
          eradiate show
      - name: Run fast tests
        run: |
          pytest -p robotframework --robot-tagstatinclude unit --robot-tagstatinclude system --robot-tagstatinclude regression --robot-tagstatinclude slow -m "not slow" ./tests
      - name: Robot report
        if: always()
        run: |
          rebot --tagstatinclude unit --tagstatinclude system --tagstatinclude regression --tagstatinclude slow --expandkeywords name:* ./output.xml
          chrome --no-sandbox --virtual-time-budget=10000 --headless --print-to-pdf=./log.pdf    ./log.html    --no-pdf-header-footer
          chrome --no-sandbox --virtual-time-budget=10000 --headless --print-to-pdf=./report.pdf ./report.html --no-pdf-header-footer
      - uses: ./.github/actions/save-ci-logs

  report:
    name: Run tests (all)
    needs: compile
    runs-on: [self-hosted, ars, ubuntu_x86_64_eradiateci_spot]
    if: github.event.pull_request.draft == false

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "recursive"
      - uses: ./.github/actions/prepare-ci
      - name: Download datasets
        run: |
          eradiate data install core
      - name: Eradiate show
        run: |
          eradiate show
      - name: Run all tests
        run: |
          pytest -p robotframework --robot-tagstatinclude unit --robot-tagstatinclude system --robot-tagstatinclude regression --robot-tagstatinclude slow ./tests
      - name: Robot report
        if: always()
        run: |
          rebot --tagstatinclude unit --tagstatinclude system --tagstatinclude regression --tagstatinclude slow --expandkeywords name:* ./output.xml
          chrome --no-sandbox --virtual-time-budget=10000 --headless --print-to-pdf=./log.pdf    ./log.html    --no-pdf-header-footer
          chrome --no-sandbox --virtual-time-budget=10000 --headless --print-to-pdf=./report.pdf ./report.html --no-pdf-header-footer
      - uses: ./.github/actions/save-ci-logs
