name: Eradiate full test report

on:
  workflow_dispatch:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]
    branches:
      - main
      - next

env:
  CC: clang-17
  CXX: clang++-17
  ERADIATE_SOURCE_DIR: ${{ github.workspace }}
  PYTHONPATH: ${{ github.workspace }}/ext/mitsuba/build/python

jobs:
  test:
    runs-on: [self-hosted, ars, ubuntu_x86_64_eradiatecompile_spot]
    if: github.event.pull_request.draft == false && github.base_ref != 'main'
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "recursive"
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .[doc,recommended,test,dev]
      - name: Build kernel
        run: |
          cmake -S ext/mitsuba -B ext/mitsuba/build -DCMAKE_BUILD_TYPE=Release -GNinja --preset eradiate
          cmake --build ext/mitsuba/build
      - name: Download datasets
        run: |
          eradiate data fetch minimal
          eradiate data fetch monotropa
          eradiate data fetch komodo
          eradiate data fetch gecko
      - name: Run all tests
        run: |
          pytest -p robotframework --robot-tagstatinclude unit --robot-tagstatinclude system --robot-tagstatinclude regression --robot-tagstatinclude slow ./tests
      - name: Robot report
        if: always()
        run: |
          rebot --expandkeywords name:* ./output.xml
          chrome --no-sandbox --virtual-time-budget=10000 --headless --print-to-pdf=./log.pdf    ./log.html    --no-pdf-header-footer
          chrome --no-sandbox --virtual-time-budget=10000 --headless --print-to-pdf=./report.pdf ./report.html --no-pdf-header-footer
      - name: Save HTML log
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: log_html
          path: ./log.html
      - name: Save HTML report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: report_html
          path: ./report.html
      - name: Save PDF log
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: log_pdf
          path: ./log.pdf
      - name: Save PDF report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: report_pdf
          path: ./report.pdf
      - name: Save test outputs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: output_xml
          path: ./output.xml
