[default.absorption_database_error_handling]
x = {missing = "ignore", scalar = "ignore", bounds = "raise"}

# Atmospheric pressure easily goes very low, but at
# these altitude, the air is very thin and so is the
# absorption coefficient ⇒ ignore ouf-of-bounds errors
p = {missing = "raise", scalar = "raise", bounds = "ignore"}

# Atmospheric temperature climbs fast above 80-100 km,
# but at these altitude, the air is very thin and so is
# the absorption coefficient
t = {missing = "raise", scalar = "raise", bounds = "ignore"}
